[package]
name = "FReader"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0"
crossterm = "0.27"
textwrap = "0.14.0"
gethostname = "0.4.0"
rustix = "0.38.44"
unicode-segmentation = "1.6.0"
home = "0.5.11"
